####################################################################
# PopulationSim Properties
####################################################################


# Algorithm/Software Configuration
# ------------------------------------------------------------------
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: False
GROUP_BY_INCIDENCE_SIGNATURE: True
USE_SIMUL_INTEGERIZER: True
USE_CVXPY: False
max_expansion_factor: 30


# Geographic Settings
# ------------------------------------------------------------------
geographies: [REGION, PUMA, MAZ]
seed_geography: PUMA


# Tracing
# ------------------------------------------------------------------
trace_geography:
  MAZ: 410961


# Data Directory
# ------------------------------------------------------------------
data_dir: group_quarters\data


# Input Data Tables
# ------------------------------------------------------------------
# input_pre_processor input_table_list
input_table_list:
  - tablename: households
    filename : seed_households.csv
    index_col: unique_hh_id
    column_map:
      hhnum: unique_hh_id
  - tablename: persons
    # expression_filename: seed_persons_expressions.csv
    filename : seed_persons.csv
    column_map:
      hhnum: unique_hh_id
    # drop mixed type fields that appear to have been incorrectly generated
    # drop_columns:
    #  - indp02
  - tablename: geo_cross_walk
    # todo: update this. It's based on 
    # Box\Modeling and Surveys\Development\Travel Model Two Development\Population Synthesis\Application\GeographicXWalk\geographicCWalk.csv
    filename : geographicCWalk.csv
    column_map:
      MTCCountyID: COUNTY
      PUMA5CE00: PUMA
    # exported from popsyn3 mysql table control_totals_maz_year_2010
    # todo: clean-up and standardize the production of this table
  - tablename: MAZ_control_data
    filename : model_year_mazData.csv
    # exported from popsyn3 mysql table control_totals_meta_year_2010
    # todo: clean-up and standardize the production of this table
  - tablename: REGION_control_data
    filename : model_year_regionData.csv


# Reserved Column Names
# ------------------------------------------------------------------
household_weight_col: PWGTP
household_id_col: unique_hh_id
total_hh_control: num_hh


# Control Specification File Name
# ------------------------------------------------------------------
control_file_name: controls_gq.csv


# Output Tables
# ------------------------------------------------------------------
# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then no tables will be written

output_tables:
  action: include
  tables:
    - summary_MAZ
    - summary_MAZ_PUMA
    - expanded_household_ids


# Synthetic Population Output Specification
# ------------------------------------------------------------------
#

output_synthetic_population:
  household_id: unique_hh_id
  households:
    filename: synthetic_households.csv
    columns:
      - SERIALNO                # Housing unit/GQ person serial number
      - PUMA                    # Public use microdata area code
      - ADJINC                  # Adjustment factor for income and earnings dollar amounts
      - WGTP                    # Housing weight
      - NP                      # Number of person records following this housing record
      - TYPE                    # Type of unit
      - ACR                     # Lot size
      - BLD                     # Units in structure
      - HHT                     # Household/family type
      - HINCP                   # Household income (past 12 months)
      - HUPAC                   # HH presence and age of children
      - NPF                     # Number of persons in family (unweighted)
      - TEN                     # Tenure
      - VEH                     # Vehicles available
      - hh_workers_from_esr     # count of employed persons in household
      - hh_income_2010          # household income in 2010 dollars, based on HINCP and ADJINC
      - gqtype                  # group quarters type: 0: household (not gq), 1 college, 2 militar, 3 other
  persons:
    filename: synthetic_persons.csv
    columns:
      - SERIALNO             # Housing unit/GQ person serial number
      - SPORDER              # Person number
      - PUMA                 # Public use microdata area code
      - PWGTP                # Person's weight
      - AGEP                 # Age
      - COW                  # Class of worker
      - MIL                  # Military service
      - RELP                 # Relationship
      - SCHG                 # Grade level attending
      - SCHL                 # Educational attainment
      - SEX                  # Sex
      - WKHP                 # Usual hours worked per week past 12 months
      - WKW                  # Weeks worked during past 12 months
      - ESR                  # Employment status recode
      - HISP                 # Recoded detailed Hispanic origin
      - naicsp07             # NAICS 2007 Industry code
      - PINCP                # Total person's income (signed)
      - POWPUMA              # Place of work PUMA
      - socp00               # SOC 2000 Occupation code
      - socp10               # SOC 2010 Occupation code
      - indp02               # Industry 2002 recode
      - indp07               # Industry 2007 recode
      - occp02               # Occupation 2002 recode
      - occp10               # Occupation 2010 recode
      - employed             # 0 or 1, based on ESR (from create_seed_population.py)

# Steps for base mode
# ------------------------------------------------------------------
run_list:
  steps:
    - input_pre_processor
    - setup_data_structures
    - initial_seed_balancing
    - meta_control_factoring
    - final_seed_balancing
    - integerize_final_seed_weights
    - sub_balancing.geography=MAZ
    - expand_households
    - summarize
    - write_tables
    - write_synthetic_population

  #resume_after: expand_households
