####################################################################
# PopulationSim Properties - FAST MODE
# Relaxed settings for faster execution during testing
####################################################################

# Algorithm/Software Configuration - RELAXED FOR SPEED
# ------------------------------------------------------------------
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: True
GROUP_BY_INCIDENCE_SIGNATURE: False
USE_SIMUL_INTEGERIZER: True
USE_CVXPY: False
max_expansion_factor: 30

# RELAXED TOLERANCES FOR FASTER EXECUTION
# ------------------------------------------------------------------
# Balancer tolerances (more relaxed)
rel_tolerance: 0.01         # Default: 0.001 (10x more relaxed)
abs_tolerance: 10.0         # Default: 1.0 (10x more relaxed)
max_iterations: 1000        # Default: 10000 (10x fewer iterations)

# Integerizer tolerances (more relaxed)
integer_tolerance: 0.1      # More relaxed integer tolerance
max_integerizer_iterations: 100  # Fewer iterations

# Geographic Settings
# ------------------------------------------------------------------
geographies: [COUNTY, PUMA, TAZ, MAZ]
seed_geography: PUMA

# Reserved Column Names
# ------------------------------------------------------------------
household_weight_col: WGTP
household_id_col: unique_hh_id
total_hh_control: numhh_gq

# Control Specification File Name
# ------------------------------------------------------------------
control_file_name: controls.csv

# Tracing - MINIMAL FOR SPEED
# ------------------------------------------------------------------
trace_geography:
  TAZ: 56
  MAZ: 10001

# Minimal debugging for speed
# ------------------------------------------------------------------
TRACE_ENABLED: False        # Disable for speed
DEBUG_DATA_PROCESSING: False

# Data Directory
# ------------------------------------------------------------------
data_dir: .

# Input Data Tables
# ------------------------------------------------------------------
input_table_list:
  - tablename: households
    filename : seed_households.csv
    index_col: unique_hh_id
    drop_columns:
      - RT
    dtype:
      HUPAC: int
      NP: int
      hhgqtype: int
      hh_workers_from_esr: int
      PUMA: int
  - tablename: persons
    filename : seed_persons.csv
    drop_columns:
      - RT
      - NAICSP
      - SOCP
      - soc
  - tablename: geo_cross_walk
    filename : geo_cross_walk_tm2.csv
  - tablename: MAZ_control_data
    filename : maz_marginals_hhgq.csv
  - tablename: TAZ_control_data
    filename : taz_marginals_hhgq.csv
  - tablename: COUNTY_control_data
    filename : county_marginals.csv

# Control Specification
# ------------------------------------------------------------------
control_file_name: controls.csv

# Model steps specification
# ------------------------------------------------------------------
models:
    - input_pre_processor
    - setup_data_structures
    - initial_seed_balancing  
    - meta_control_factoring
    - final_seed_balancing
    - integerize_final_seed_weights
    - expand_households
    - summarize

resume_after:

# Output Tables
# ------------------------------------------------------------------
output_tables:
  action: include
  tables:
    - summary_COUNTY
    - summary_PUMA  
    - summary_TAZ
    - summary_MAZ
    - households_PUMA
    - persons_PUMA
    - households_TAZ
    - persons_TAZ
    - households_MAZ
    - persons_MAZ

# Tracing
# ------------------------------------------------------------------
# output_tables with all tables  
#output_tables:
#  action: include
#  tables:
#    - checkpoints.csv
#    - summary_COUNTY
#    - summary_PUMA  
#    - summary_TAZ
#    - summary_MAZ
#    - households_PUMA
#    - persons_PUMA
#    - households_TAZ
#    - persons_TAZ
#    - households_MAZ
#    - persons_MAZ
#    - PUMA_weights
#    - COUNTY_controls
#    - PUMA_controls  
#    - TAZ_controls
#    - MAZ_controls
#    - crosswalk
#    - incidence_table

# Steps for base mode
# ------------------------------------------------------------------
run_list:
  steps:
    - input_pre_processor
    - setup_data_structures
    - initial_seed_balancing
    - meta_control_factoring
    - final_seed_balancing
    - integerize_final_seed_weights
    - sub_balancing.geography=TAZ
    - sub_balancing.geography=MAZ
    - expand_households
    - summarize
    - write_tables
    - write_synthetic_population

  #resume_after: expand_households

# chunking for memory management  
# ------------------------------------------------------------------
chunk_training_mode: disabled
