####################################################################
# PopulationSim Properties
####################################################################


# Algorithm/Software Configuration
# ------------------------------------------------------------------
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: False
GROUP_BY_INCIDENCE_SIGNATURE: True
USE_SIMUL_INTEGERIZER: True
USE_CVXPY: False
max_expansion_factor: 30


# Geographic Settings
# ------------------------------------------------------------------
geographies: [COUNTY, PUMA, TAZ, MAZ]
seed_geography: PUMA


# Tracing
# ------------------------------------------------------------------
trace_geography:
  TAZ: 56
  MAZ: 10001


# Data Directory
# ------------------------------------------------------------------
data_dir: households\data


# Input Data Tables
# ------------------------------------------------------------------
# input_pre_processor input_table_list
input_table_list:
  - tablename: households
    filename : seed_households.csv
    index_col: unique_hh_id
  - tablename: persons
    filename : seed_persons.csv
    # drop mixed type fields that appear to have been incorrectly generated
    # drop_columns:
    #  - indp02
  - tablename: geo_cross_walk
    filename : geo_cross_walk.csv
    # created by create_baseyear_controls.py
  - tablename: MAZ_control_data
    filename : model_year_MAZ_controls.csv
    # created by create_baseyear_controls.py
  - tablename: TAZ_control_data
    filename : model_year_TAZ_controls.csv
    # created by create_baseyear_controls.py
  - tablename: COUNTY_control_data
    filename : model_year_COUNTY_controls.csv
    # created by create_baseyear_controls.py


# Reserved Column Names
# ------------------------------------------------------------------
household_weight_col: WGTP
household_id_col: unique_hh_id
total_hh_control: num_hh


# Control Specification File Name
# ------------------------------------------------------------------
control_file_name: controls.csv


# Output Tables
# ------------------------------------------------------------------
# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then no tables will be written

output_tables:
  action: include
  tables:
    - summary_MAZ
    - summary_TAZ
    - summary_COUNTY_1
    - summary_COUNTY_2
    - summary_COUNTY_3
    - summary_COUNTY_4
    - summary_COUNTY_5
    - summary_COUNTY_6
    - summary_COUNTY_7
    - summary_COUNTY_8
    - summary_COUNTY_9
    - expanded_household_ids


# Synthetic Population Output Specification
# ------------------------------------------------------------------
#

output_synthetic_population:
  household_id: unique_hh_id
  households:
    filename: synthetic_households.csv
    columns:
      - SERIALNO                # Housing unit/GQ person serial number
      - PUMA                    # Public use microdata area code
      - ADJINC                  # Adjustment factor for income and earnings dollar amounts
      - WGTP                    # Housing weight
      - NP                      # Number of person records following this housing record
      - TYPE                    # Type of unit
      - ACR                     # Lot size
      - BLD                     # Units in structure
      - HHT                     # Household/family type
      - HINCP                   # Household income (past 12 months)
      - HUPAC                   # HH presence and age of children
      - NPF                     # Number of persons in family (unweighted)
      - TEN                     # Tenure
      - VEH                     # Vehicles available
      - hh_workers_from_esr     # count of employed persons in household
      - hh_income_2010          # household income in 2010 dollars, based on HINCP and ADJINC
      - gqtype                  # group quarters type: 0: household (not gq), 1 college, 2 militar, 3 other
  persons:
    filename: synthetic_persons.csv
    columns:
      - SERIALNO             # Housing unit/GQ person serial number
      - SPORDER              # Person number
      - PUMA                 # Public use microdata area code
      - PWGTP                # Person's weight
      - AGEP                 # Age
      - COW                  # Class of worker
      - MIL                  # Military service
      - RELP                 # Relationship
      - SCHG                 # Grade level attending
      - SCHL                 # Educational attainment
      - SEX                  # Sex
      - WKHP                 # Usual hours worked per week past 12 months
      - WKW                  # Weeks worked during past 12 months
      - ESR                  # Employment status recode
      - HISP                 # Recoded detailed Hispanic origin
      - naicsp07             # NAICS 2007 Industry code
      - PINCP                # Total person's income (signed)
      - POWPUMA              # Place of work PUMA
      - socp00               # SOC 2000 Occupation code
      - socp10               # SOC 2010 Occupation code
      - indp02               # Industry 2002 recode
      - indp07               # Industry 2007 recode
      - occp02               # Occupation 2002 recode
      - occp10               # Occupation 2010 recode
      - employed             # 0 or 1, based on ESR (from create_seed_population.py)

# Steps for base mode
# ------------------------------------------------------------------
run_list:
  steps:
    - input_pre_processor
    - setup_data_structures
    - initial_seed_balancing
    - meta_control_factoring
    - final_seed_balancing
    - integerize_final_seed_weights
    - sub_balancing.geography=TAZ
    - sub_balancing.geography=MAZ
    - expand_households
    - summarize
    - write_tables
    - write_synthetic_population

  #resume_after: expand_households
