####################################################################
# PopulationSim Properties
####################################################################


# Algorithm/Software Configuration
# ------------------------------------------------------------------
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: False
GROUP_BY_INCIDENCE_SIGNATURE: True
USE_SIMUL_INTEGERIZER: True
USE_CVXPY: False
max_expansion_factor: 30


# Geographic Settings
# ------------------------------------------------------------------
geographies: [COUNTY, PUMA, TAZ, MAZ]
seed_geography: PUMA


# Tracing
# ------------------------------------------------------------------
trace_geography:
  TAZ: 56
  MAZ: 10001


# Data Directory
# ------------------------------------------------------------------
data_dir: data


# Input Data Tables
# ------------------------------------------------------------------
# input_pre_processor input_table_list
input_table_list:
  - tablename: households
    filename : seed_households.csv
    index_col: unique_hh_id
    column_map:
      hhnum: unique_hh_id
  - tablename: persons
    # expression_filename: seed_persons_expressions.csv
    filename : seed_persons.csv
    column_map:
      hhnum: unique_hh_id
      SPORDER: SPORDER
    # drop mixed type fields that appear to have been incorrectly generated
    # drop_columns:
    #  - indp02
  - tablename: geo_cross_walk
    # todo: update this. It's based on 
    # Box\Modeling and Surveys\Development\Travel Model Two Development\Population Synthesis\Application\GeographicXWalk\geographicCWalk.csv
    filename : geographicCWalk.csv
    column_map:
      MTCCountyID: COUNTY
      PUMA5CE00: PUMA
    # exported from popsyn3 mysql table control_totals_taz_year_2010
    # todo: clean-up and standardize the production of this table
  - tablename: TAZ_control_data
    filename : 2010_tazData.csv
    # exported from popsyn3 mysql table control_totals_maz_year_2010
    # todo: clean-up and standardize the production of this table
  - tablename: MAZ_control_data
    filename : 2010_mazData.csv
    # exported from popsyn3 mysql table control_totals_meta_year_2010
    # todo: clean-up and standardize the production of this table
  - tablename: COUNTY_control_data
    filename : 2010_countyData.csv


# Reserved Column Names
# ------------------------------------------------------------------
household_weight_col: WGTP
household_id_col: unique_hh_id
total_hh_control: num_hh


# Control Specification File Name
# ------------------------------------------------------------------
control_file_name: controls.csv


# Output Tables
# ------------------------------------------------------------------
# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then no tables will be written

output_tables:
  action: include
  tables:
    - summary_MAZ
    - summary_TAZ
    - summary_TAZ_PUMA
    - expanded_household_ids


# Synthetic Population Output Specification
# ------------------------------------------------------------------
#

output_synthetic_population:
  household_id: household_id
  households:
    filename: synthetic_households.csv
    columns:
      - NP
      - hh_income_2010
      - hh_workers
      - HUPAC
  persons:
    filename: synthetic_persons.csv
    columns:
      - SPORDER
      - AGEP
      - occupation


# Steps for base mode
# ------------------------------------------------------------------
run_list:
  steps:
    - input_pre_processor
    - setup_data_structures
    - initial_seed_balancing
    - meta_control_factoring
    - final_seed_balancing
    - integerize_final_seed_weights
    - sub_balancing.geography=TAZ
    - sub_balancing.geography=MAZ
    - expand_households
    - summarize
    - write_tables
    - write_synthetic_population

  #resume_after: expand_households
